### PR TITLE
Sips Office JSON, frictionless, 3DSv2

### LINKED ISSUE #6: SipsEnvironment and Inheritance.
Actually Worldline\Sips\Common\SipsEnvironment work only for the merchant Atos.
If we want to use it for another merchant, we need to change what is defined for the properties $possibleEnvironments and $environment.
But these properties are private (and not protected).

To extend it, you need to completely rewrite the whole class.

I propose de change the SipsClient to make it possible to be extended properly, and to create others environnements for others merchants : 
MercanetEnvironment => https://documentation.mercanet.bnpparibas.net/index.php/Connecteur_POST
SogenActifEnvironment => https://sogenactif.documentation.sogenactif.com/fr/paypage-post.html

### PR DESCRIPTION
**Pull request by guiled**
Fix #6 
Add many new features, mainly about Sips Office Json

### CODE REVIEW

**Comment by nicolasros** [comment]
Hi Guislain,

thanks a lot for all the work you have put into this!
You have added some missing features and that is greatly appreciated.

However, i will not merge your code into master at this moment.
Some of the changes might break the existing integrations, if they update without checking.
Because of that, i have merged your changes into the development branch for some additional testing over the coming week.
Once we are happy with these tests, i will merge the development branch into master.

**Comment by guiled** [comment]
Hi !
I totally understand the reasons to not integrate it directly into master ! (production first !)
I have just updated the PR to integrate the last commits and resolve conflicts.
Thank you for your review

**Comment by simondaigre** [comment]
Hi @nicolasros, any news about merging this great PR ?

**Comment by simondaigre** [comment]
Ping @CrlH

**Comment by guiled** [comment]
Hello @WorldlineOfficial  Do you still need this PR or should I close it ?

**Comment by guiled** [comment]
Nobody will merge it… So I close it.
So long, and thanks for all the SIPS…

**Pull request closed without merging**
